[build]
  base = "frontend"  # This should be the relative path to the directory where your code resides.
  publish = "build"  # Where the built files will be deployed from.
  command = "npm run build"  # Or whatever build command you're using.
